num1 = int(input("Insira um número: ")) #AQUI ESTÁ SENDO INSERIDO O NÚMERO DO USUÁRIO PELO INPUT A SER DOBRADO
num2 = num1*2 #AQUI ESTÁ SENDO INFORMADO O CÁLCULO USADO PARA DOBRAR
print(f"O dobro dele é: {num2}") #AQUI MOSTRARÁ O RESULTADO DO CÁLCULO USANDO PRINT NO TERMINAL